"""
QA Splits — Home Credit Default Risk
====================================

Validates the integrity of the data splits generated by shared_pipeline.py.

Checks:
1. File existence and sizes.
2. No overlap between D_L (approved) and D_R (rejected) IDs.
3. Default rates match expectations (D_R > D_L).
4. Feature consistency across all splits.
5. No target leakage in D_R_features.
"""
import pandas as pd
import numpy as np
import json
from pathlib import Path
import config

def run_qa():
    print("--- QA: Validating Data Splits ---")
    
    # Load metadata
    with open(config.SPLIT_METADATA, "r") as f:
        meta = json.load(f)
    print(f"Metadata loaded. Cutoff: {meta['cutoff_value']:.4f}")

    # Load splits
    splits = {
        "D_L_train": pd.read_parquet(config.SPLIT_DL_TRAIN),
        "D_L_val": pd.read_parquet(config.SPLIT_DL_VAL),
        "D_L_test": pd.read_parquet(config.SPLIT_DL_TEST),
        "D_R_features": pd.read_parquet(config.SPLIT_DR_FEATURES),
        "D_R_truth": pd.read_parquet(config.SPLIT_DR_TRUTH),
    }
    
    # 1. Size checks
    print("\n[Size Check]")
    total_dl = len(splits["D_L_train"]) + len(splits["D_L_val"]) + len(splits["D_L_test"])
    print(f"D_L Total: {total_dl} (Expected: {meta['d_l_total']})")
    print(f"D_R Total: {len(splits['D_R_features'])} (Expected: {meta['d_r_size']})")
    
    assert len(splits["D_R_features"]) == len(splits["D_R_truth"])
    assert total_dl == meta["d_l_total"]
    print("✅ Sizes match metadata.")

    # 2. Default Rates
    print("\n[Default Rate Check]")
    dr_dl = pd.concat([splits["D_L_train"], splits["D_L_val"], splits["D_L_test"]])["TARGET"].mean()
    dr_dr = splits["D_R_truth"]["TARGET"].mean()
    print(f"D_L Default Rate: {dr_dl:.2%}")
    print(f"D_R Default Rate: {dr_dr:.2%}")
    
    if dr_dr > dr_dl:
        print("✅ D_R is higher risk than D_L (Expected).")
    else:
        print("⚠️ WARNING: D_R risk is NOT higher than D_L. Check cutoff logic.")

    # 3. Leakage Check
    print("\n[Leakage Check]")
    if "TARGET" in splits["D_R_features"].columns:
        print("❌ CRITICAL: TARGET found in D_R_features!")
    else:
        print("✅ No TARGET in D_R_features.")

    # 4. Feature Consistency
    print("\n[Feature Consistency]")
    cols_train = set(splits["D_L_train"].columns)
    cols_dr = set(splits["D_R_features"].columns)
    
    # D_L has TARGET, D_R does not. Checks common features.
    common_cols = cols_train - {"TARGET"}
    dr_cols_check = cols_dr
    
    if common_cols == dr_cols_check:
        print(f"✅ All {len(common_cols)} features match between D_L and D_R.")
    else:
        diff = common_cols.symmetric_difference(dr_cols_check)
        print(f"❌ Mismatch in features: {diff}")

    print("\n--- QA Complete ---")

if __name__ == "__main__":
    run_qa()
